// The emulator-backed tests, run by `yarn test:emulated`.
//
// Generated by tools/setup-emulator.mjs. Inherits vitest.config.js so aliases,
// plugins and environment stay in one place, and replaces only the file set.
// Nothing here changes what `yarn test:run` does.
import { defineConfig } from 'vitest/config';
import base from './vitest.config.js';

const resolved = typeof base === 'function' ? base({ mode: 'test', command: 'serve' }) : base;

export default defineConfig({
  ...resolved,
  test: {
    ...(resolved.test || {}),
    include: ['src/test/emulated/**/*.test.{js,mjs}'],
    exclude: ['**/node_modules/**', '**/dist/**'],
    // One emulator database, shared by every file in here.
    fileParallelism: false,
  },
});
