// Emulator-backed tests for movie-hat.
//
// Generated by tools/setup-emulator.mjs. This one only proves the harness
// works: the real rules compile and load, and an authenticated client can be
// built against them. It earns its keep the moment you add a case for a write
// this app actually makes.
//
// Run with: yarn test:emulated   (NOT yarn test:run - it needs the emulator)
//
// The reason this directory exists: on 2026-09-17 seven games had silently
// recorded nothing for three weeks because their write was refused and the
// error was swallowed. Unit tests stop at the edge of Firebase. These do not.
import {
  describe, it, expect, beforeAll, afterAll,
} from 'vitest';
import { initializeTestEnvironment } from '@firebase/rules-unit-testing';
import { readFileSync } from 'fs';
import { ref, get } from 'firebase/database';

let testEnv;

beforeAll(async () => {
  testEnv = await initializeTestEnvironment({
    projectId: 'movie-hat-9c418',
    database: {
      rules: readFileSync('database.rules.json', 'utf8'),
      host: '127.0.0.1',
      port: 9000,
    },
  });
});

afterAll(async () => { if (testEnv) await testEnv.cleanup(); });

describe('movie-hat: the emulator harness', () => {
  it('loads this app\'s real database rules', async () => {
    // initializeTestEnvironment throws if the rules do not compile, so
    // reaching here already proves they parse.
    expect(testEnv).toBeTruthy();
  });

  it('gives an authenticated client a working handle', async () => {
    const db = testEnv.authenticatedContext('someone').database();
    // A read that rules may well deny is fine - we are checking the harness,
    // not the answer. It must not THROW on connection.
    await expect(get(ref(db, '/')).catch(() => 'denied')).resolves.toBeDefined();
  });
});
